mklink /J "D:\admin\dotfiles" "D:\admin\Development\dotfiles"
mklink %HOME%"\_vimrc" "D:\admin\Development\dotfiles\vim\_vimrc"
mklink %HOME%"\_gvimrc" "D:\admin\Development\dotfiles\vim\_gvimrc"
mklink %HOME%"\.bashrc" "D:\admin\Development\dotfiles\.bashrc"
mklink %HOME%"\.bashrc" "D:\admin\Development\dotfiles\.bashrc"
mklink %HOME%"\.gitconfig" "D:\admin\Development\dotfiles\.gitconfig"
mklink %HOME%"\.gitignore" "D:\admin\Development\dotfiles\.gitignore"
mklink "D:\admin\_vrapperrc" "D:\admin\Development\dotfiles\eclipse\_vrapperrc"
mklink "D:\admin\.vrapperrc.local" "D:\admin\Development\dotfiles\eclipse\_vrapperrc.win"

git config user.name "assout"
git config user.email "assout@users.noreply.github.com"
