---
  extends: "airbnb"
  env:
    # browser: true
    es6: true
    # jquery: true
    webextensions: true
  rules:
    strict: 0
    import/no-unresolved: 0
    require-jsdoc: 0 # TODO 暫定
    no-console: 0
    no-unused-vars: [2, {"vars": "all", "args": "none"}]
    func-names: 0

